"""create tables again

Revision ID: 3db75226a3e4
Revises: 
Create Date: 2024-12-15 23:55:51.621992

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import sessionmaker	

# revision identifiers, used by Alembic.
revision: str = '3db75226a3e4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('role_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('role_code', sa.String(length=40), nullable=False),
    sa.Column('can_lead', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_table('collaborators',
    sa.Column('collaborator_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('registration_code', sa.String(length=40), nullable=False),
    sa.Column('leader_name', sa.String(length=40), nullable=True),
    sa.Column('leader_code', sa.String(length=40), nullable=True),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('salary', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('status_hired', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.PrimaryKeyConstraint('collaborator_id')
    )
    # ### end Alembic commands ###

    roles = """
    INSERT INTO roles (role_id, name, role_code, can_lead)
    VALUES
    (1, 'junior developer', 'JD', false),
    (2, 'mid-level developer', 'MD', false),
    (3, 'senior developer', 'SD', false),
    (4, 'tech lead', 'TL', true)
    """
    
    Session = sessionmaker(bind=op.get_bind())
    session = Session()
    session.execute(sa.text(roles))
    session.commit()

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collaborators')
    op.drop_table('roles')
    # ### end Alembic commands ###
