"""run models migrations

Revision ID: 8d2419365fb9
Revises: 
Create Date: 2024-12-15 19:27:13.576272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d2419365fb9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('role_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('role_code', sa.String(length=40), nullable=False),
    sa.Column('can_lead', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_table('collaborators',
    sa.Column('collaborator_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('registration_code', sa.String(length=20), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('salary', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('status_hired', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.PrimaryKeyConstraint('collaborator_id')
    )
    op.create_table('collaborator_hierarchy',
    sa.Column('hierarchy_id', sa.BigInteger(), nullable=False),
    sa.Column('subordinate_id', sa.BigInteger(), nullable=False),
    sa.Column('supervisor_code', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['subordinate_id'], ['collaborators.collaborator_id'], ),
    sa.PrimaryKeyConstraint('hierarchy_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collaborator_hierarchy')
    op.drop_table('collaborators')
    op.drop_table('roles')
    # ### end Alembic commands ###
